version: '3.8'

services:
  frontend-dev:
    container_name: uptalk_frontend_dev
    image: uptalk-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./:/app/frontend
      - /app/frontend/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true