version: "3.9"

services:
  frontend:
    restart: always
    container_name: uptalk_frontend
    image: wenwen357951/uptalk-frontend
    build:
      context: uptalk_vue
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - postgres
      - tomcat
    networks:
      - uptalk

networks:
  uptalk:
    name: uptalk
